<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup>
  <None Update="..\config.inf">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </None>
</ItemGroup>

<ItemGroup>
  <PackageReference Include="BouncyCastle.NetCore" Version="2.2.1" />
</ItemGroup>


  <Target Name="ForceCleanPublishDir" BeforeTargets="BeforePublish">
    <Exec Condition="Exists('$(PublishDir)')" Command="powershell -NoProfile -Command &quot;$retry=3; do { try { Remove-Item -LiteralPath '$(PublishDir)' -Recurse -Force -ErrorAction Stop; break } catch { $retry--; if ($retry -eq 0) { throw }; Start-Sleep -Seconds 2 } } while ($retry -gt 0)&quot;" />
  </Target>

</Project>
